# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
#   $RNFirebaseAsStaticFramework = true
# end

target 'MiroLang' do
  config = use_native_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseFirestore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'MiroLangTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Workaround for BoringSSL-GRPC: clang misparses '-GCC_WARN_INHIBIT_ALL_WARNINGS' as '-G CC_WARN...'
    installer.pods_project.targets.each do |target|
      if target.name == 'BoringSSL-GRPC'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            flags = file.settings['COMPILER_FLAGS'].split
            flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
            file.settings['COMPILER_FLAGS'] = flags.join(' ')
          end
        end
      end
    end

    # Silence Clang 16+ warnings-as-errors in gRPC-Core, gRPC-C++, abseil etc.
    grpc_targets = ['gRPC-Core', 'gRPC-C++', 'abseil', 'BoringSSL-GRPC', 'leveldb-library']
    installer.pods_project.targets.each do |target|
      if grpc_targets.include?(target.name)
        target.build_configurations.each do |config|
          existing = config.build_settings['OTHER_CFLAGS'] || '$(inherited)'
          existing = existing.join(' ') if existing.is_a?(Array)
          config.build_settings['OTHER_CFLAGS'] = existing + ' -Wno-missing-template-arg-list-after-template-kw -Wno-error=missing-template-arg-list-after-template-kw -Wno-error'
          existing_cpp = config.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
          existing_cpp = existing_cpp.join(' ') if existing_cpp.is_a?(Array)
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = existing_cpp + ' -Wno-missing-template-arg-list-after-template-kw -Wno-error=missing-template-arg-list-after-template-kw -Wno-error'
        end
      end
    end
  end
end
